### ISSUE TITLE
Directory Support

### ISSUE THREAD

**Issue by ksmithut** [stormpath/stormpath-express#72]
Please correct me if I'm wrong, but right now the module is tied to an application's main directory. It would be nice to have support to choose other directories in an application to use.

Here's my use case: I am building a microservice architecture with each microservice using express-stormpath's oauth2 functionality. I've gotten it to work wonderfully with an application. There will only be a handleful of api consumers (developers) for each microservice, so giving each microservice it's own directory in a single application would be most ideal so we don't have to create a new application for every microservice when each microservice is really only going to have around 5-10 api developers.

**Comment by rdegges** [comment]
Heyo -- this is actually supported already -- but the way it works is a bit 'different'.

When you have a Stormpath Application, you can map as many Directories to it as you want. By default, Express-Stormpath will lookup / retrieve your Application, because things like API authentication / etc are all based off the Application object, not a directory object.

Let's say you have 5 Directories mapped to an Application (in order):

- Directory 1
- Directory 2
- Directory 3
- Directory 4
- Directory 5

If you have created an IDENTICAL user account in each Application, then when we generate an API key / etc. we'll use the account from the first linked Directory (Directory 1, in this case).

If you have different user accounts in each Application, then we'll find and use the right one automatically.

So -- this should already be working for you. What I'd do is create one Directory for each microservice, and however many unique accounts in that Directory for your consumers.

**Comment by ksmithut** [comment]
That's awesome, thanks :) I'll come back if it doesn't work, but you explained it well and it makes sense that it would work.

**Comment by ksmithut** [comment]
@rdegges so if you find and use the right one automatically, is there no way to restrict a user from Directory 1 from a microservice that is meant to be using Directory 2?

**Comment by rdegges** [comment]
That's correct -- there's no way to restrict it. This was done on purpose though -- as a central design decision.

EG: If you want to have truly separate 'applications', then you should simply create multiple Applications and map as many directories to those as you'd like.

The idea of an Application is to be the central access point for one codebase / app / whatever.

When I build SOA stuff myself, I typically create one Application/Directory for each service.

For instance:

- 1 App / Directory called 'logs' for my logging service.
- 1 App / Directory called 'billing' for my billing service.
- 1 App / Directory called 'storage' for my storage service.
- etc.

-Randall
