### ISSUE TITLE
Not all request are cached

### ISSUE THREAD

**Issue by suryod** [stormpath/stormpath-express#94]
Hi,

I'm trying to perform this request in my express middleware:

// req.user is available through Stormpath's middleware.
req.user.getGroups({expand: 'customData'}, function (err, groups) {
});

The request url would be something like: https://api.stormpath.com/v1/accounts/{{accountId}}/groups. I'd expect the request will be cached like other request so I trying to verify it from Redis Desktop Manager. But I'm unable to find the key like above there.

![screen shot 2015-09-22 at 9 50 59 am](https://cloud.githubusercontent.com/assets/445713/10010041/7f1e7950-610f-11e5-98d5-3e4d91425bc7.png)

(First row doesn't has /groups at the end of the url, I think it was the cache entry for account information).

Thank you,
Indra

**Comment by rdegges** [comment]
Hi Indra,

So, after thinking about this -- this is actually the desired library behavior. We made a decision to only cache direct object hrefs -- not collections. This is because the collections change so frequently it would be very very difficult to invalidate them in memory effectively.

We're working on solving this at the core Node SDK level, but for now we won't be adding caching for collections.

**Comment by suryod** [comment]
Hi Randall,

Perhaps you can cache accounts/:id/groups as well since I believe it's not changed frequently. However, I appreciate your decision.
